paths:
  - '**/*'
  
patterns:
  datadog_api_key:
    pattern: '[a-f0-9]{32}'
    description: 'Datadog API Key'
    
  datadog_app_key:
    pattern: '[a-f0-9]{40}'
    description: 'Datadog Application Key'
    
alerts:
  - type: email
  - type: issue
    assignees:
      - ${{ github.repository_owner }}
      
actions:
  - name: revoke_datadog_key
    description: 'Automatically revoke exposed Datadog API key'
    url: ${{ secrets.DATADOG_KEY_ROTATION_WEBHOOK }}
    
ignore:
  - '**/*.test.js'
  - '**/*.test.ts'
  - '**/test/**'
  - '**/tests/**'
