services:
  # Testing service for running sequential web tests
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules  # Prevent node_modules from being overwritten
    environment:
      - NODE_ENV=test
      - DEBUG=false
      - TEST_URL=http://dev:4321  # Point tests to the dev service
      - PYTHON=/usr/bin/python3  # Help node-gyp find Python
    depends_on:
      - dev
    networks:
      - ai-tools-network
    # Don't start automatically
    profiles: [test]
    # Expose DD API key when provided
    env_file:
      - .env.local

  # Development service with hot-reloading
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4321-4325:4321-4325"  # Expose multiple ports for Astro's automatic port shifting
    volumes:
      # Mount everything needed for development with hot-reloading
      - ./:/app
      - /app/node_modules  # Prevent node_modules from being overwritten
      - /app/dist         # Prevent dist from being overwritten
    environment:
      - NODE_ENV=development
      - PYTHON=/usr/bin/python3  # Help node-gyp find Python
    restart: unless-stopped
    networks:
      - ai-tools-network
    # Show log output in console
    tty: true
    stdin_open: true
    command: npm run dev -- --host 0.0.0.0

  # Production preview service
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - ai-tools-network

networks:
  ai-tools-network:
    driver: bridge
