# docker-compose-test.yml for AI Tools Lab visual testing
version: '3.8'

services:
  # Test environment with Vitest and Datadog integration
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_APP_KEY=${DD_APP_KEY}
      - NODE_ENV=test
      - SERVER_PORT=4321
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/dist
      - ./test-results:/app/test-results
      - ./tests/screenshots:/app/tests/screenshots
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - dev-server
      - ollama
    networks:
      - test-network
    command: npm run test:visual

  # Development server for testing against local
  dev-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    ports:
      - "4321:4321"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/dist
    networks:
      - test-network
    command: npm run dev

  # Ollama service for ML-powered visual comparison
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama-data:/root/.ollama
    networks:
      - test-network
    restart: unless-stopped

  # Datadog agent for monitoring and test reporting
  datadog-agent:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=datadoghq.com
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_DOCKER_LABELS_AS_TAGS=true
      - DD_DOCKER_ENV_AS_TAGS=true
      - DD_TAGS="project:ai-tools-lab,env:test"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    networks:
      - test-network
    depends_on:
      - test

networks:
  test-network:
    driver: bridge
