[build]
  command = "./scripts/build-safe.sh"
  publish = "dist"
  functions = "proxy"

# Explicitly specify the production branch
[context.production]
  command = "./scripts/build-safe.sh"
  publish = "dist"

# Specify that the test branch should be treated as production
[context.test]
  command = "./scripts/build-safe.sh"
  publish = "dist"

# Development settings
[dev]
  functions = "proxy"
  
# URL pattern redirects for compatibility between test and production environments
[[redirects]]
  from = "/pages/about"
  to = "/about"
  status = 301

[[redirects]]
  from = "/pages/resources"
  to = "/resources"
  status = 301

[[redirects]]
  from = "/pages/observations"
  to = "/observations"
  status = 301

[[redirects]]
  from = "/about"
  to = "/pages/about"
  status = 200
  force = true

[[redirects]]
  from = "/resources"
  to = "/pages/resources"
  status = 200
  force = true

[[redirects]]
  from = "/observations"
  to = "/pages/observations"
  status = 200
  force = true

[[redirects]]
  from = "/api/datadog/*"
  to = "/.netlify/functions/datadog-proxy"
  status = 200
  force = true
  
# Custom 404 page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404