[build]
  command = "npm run build"
  publish = "dist"
  functions = "proxy"

[dev]
  functions = "proxy"
  
[[redirects]]
  from = "/api/datadog/*"
  to = "/.netlify/functions/datadog-proxy"
  status = 200
  force = true
  
# Handle 404s by redirecting to index.html (SPA fallback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200