[build]
  command = "./scripts/build-safe.sh"
  publish = "dist"
  functions = "proxy"

# Explicitly specify the production branch
[context.production]
  command = "./scripts/build-safe.sh"
  publish = "dist"

# Specify that the test branch should be treated as production
[context.test]
  command = "./scripts/build-safe.sh"
  publish = "dist"

# Development settings
[dev]
  functions = "proxy"
  
[[redirects]]
  from = "/api/datadog/*"
  to = "/.netlify/functions/datadog-proxy"
  status = 200
  force = true
  
# Custom 404 page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404