apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node
          image: "{{ .Values.node.image.repository }}:{{ .Values.node.image.tag }}"
          command: {{ .Values.node.command | toJson }}
          env:
            - name: NODE_ENV
              value: {{ .Values.node.env.NODE_ENV | quote }}
          ports:
            - containerPort: 4321
          volumeMounts:
            - name: static-content
              mountPath: /app/dist
          resources:
            {{- toYaml .Values.node.resources | nindent 12 }}
      volumes:
        - name: static-content
          hostPath:
            path: ./dist
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: node
spec:
  type: ClusterIP
  ports:
    - port: 4321
      targetPort: 4321
  selector:
    app: node
