version: '3.8'

services:
  build-benchmark:
    build:
      context: ../..
      dockerfile: Dockerfile.test
    volumes:
      - ../../node_modules:/app/node_modules
      - ../scripts:/app/scripts
      - ../results:/app/results
    environment:
      - NODE_ENV=test
      - BENCHMARK_TOOLS=all
      - DD_ENV=test
      - DD_SERVICE=ai-tools-benchmark
      - DD_VERSION=${DD_VERSION:-local}
      - DD_TAGS=project:ai-tools,env:test
    profiles: [benchmark]
    command: ["node", "-r", "/app/utils/error-handler-init.js", "/app/scripts/build-tools-benchmark.js"]
    labels:
      com.datadoghq.ad.logs: '[{"source":"nodejs", "service":"ai-tools-benchmark"}]'
      com.datadoghq.tags.service: 'ai-tools-benchmark'

  rspack-benchmark:
    build:
      context: ../..
      dockerfile: Dockerfile.test
    volumes:
      - ../../node_modules:/app/node_modules
      - ../scripts:/app/scripts
      - ../results:/app/results
    environment:
      - NODE_ENV=test
      - BENCHMARK_TOOLS=rspack
      - DD_ENV=test
      - DD_SERVICE=ai-tools-benchmark-rspack
      - DD_VERSION=${DD_VERSION:-local}
      - DD_TAGS=project:ai-tools,env:test,bundler:rspack
    command: ["node", "-r", "/app/utils/error-handler-init.js", "/app/scripts/build-tools-benchmark.js"]
    profiles: [rspack]
